### ISSUE TITLE
Организовать наличие всех необходимых данных

### ISSUE THREAD

**Issue by ivansglazunov** [styleschool/imagemaker#1]
Все данные которые могут быть нужны, исчерпывающе должны быть в рамках проекта.

**Comment by romankrebs** [comment]
Тезисно, какие информационные секции на странице необходимы:
1. дата начала курса, его продолжительность
2. программа курса (в виде расписания, или описания программы)
3. стоимость и условия оплаты (возможные варианты, рассрочка, кредит или индивидуальные предложения)
4. описание курса
5. информация о преподавателях
6. отзывы студентов об этом курсе
7. визуальные материалы с предыдущего подобного курса (фотографии, видео) -- если есть
8. варианты обучения (очно, дистанционно, группы выходного дня и т.п.)
9. форма обратной связи, или "задать вопрос"

**Comment by Aruseli** [comment]
https://73k57wy22x.codesandbox.io/ по данной ссылки собраны данные, которые могут выходить, своего рода "скелетом"-шаблоном для общего понимания создания страниц под образовательные тематики. Давайте обсудим)

**Comment by romankrebs** [comment]
@Aruseli посмотрел по ссылке. Беру эту информацию в работу.
