### ISSUE TITLE
Анализ данных яндекс-метрики по странице "Имиджмейкер. Второе высшее"

### ISSUE THREAD

**Issue by romankrebs** [styleschool/imagemaker#3]
Проведя небольшой анализ посещений страницы "Имиджмейкер. Второе высшее" (ИВВ), я сделал несколько наблюдений и, на их основе, хочу предложить некоторые изменения. Выставляю это на обсуждение.
Наблюдения по карте кликов:

1- много кликают на "формы обучения"
2- много кликают на "цена успеха"
3- кликают на подсказку "ответим на все вопросы по обучению"
4- кликают на кнопку "узнать стоимость"
5- кликают на баннер с рассрочкой внизу страницы
6- лидеры кликов в футере меню: контакты, запись на обучение, о школе (перечислены в порядке частоты кликов)
7- из ссылок на соцсети кликают ТОЛЬКО на инстаграм и вайбер
8- из выпускников, больше кликают на тех, кто на фотографиях выглядит стильнее и красивее
9- мало кликается кнопка "Записаться на собеседование"

Выводы из этих наблюдений:

1, 2- людей интересуют подробности описания форм обучения и стоимости
3 - хорошо бы настроить чат
4, 5 - возможно, информацию о рассрочке надо включить в блок информации о стоимости обучения в виде:
```
стоимость обучения 20 000 руб. *
...
* Возможна оплата в рассрочку ...
```
6- до подвала доходят и даже пользуются нижним меню, хотя, не так активно, как верхним
7- этим соцсетям надо уделить особое внимание
8- надо размещать те фотографии, которые больше соответствуют тематике моды и стиля
9- кнопка шириной во всю страницу смотрится, как заголовок

Наблюдения на основе вебвизора:

- люди читают информацию на сайте (особенно, интересуют блоки форма обучения, и 4 блока описания обучения)
- много пользователей отваливается на блоке Краткое описание программы.

Выводы:

- информацию по описанию программы надо сделать более эмоциональной, а не подробной и сухой.
Рядом с описанием сроков обучения на длинной программе надо сделать какую-то ссылку на короткие курсы похожей тематики.

**Comment by Aruseli** [comment]
@romankrebs это же не кнопка? Это доказывает, что стоимость нужно выносить наружу, а не прятать за кнопками

> много кликают на "цена успеха"

**Comment by romankrebs** [comment]
Настя, согласен. Я только "за".
